[project]
name = "sales_pipeline"
version = "1.0"

[materialization]
bronze = "parquet"
silver = "parquet"
gold = "parquet"

[output]
destination = "local"

[output.local]
bronze_path = "output/bronze"
silver_path = "output/silver"
gold_path = "output/gold"
